# App
spring.application.name=worksphere

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/worksphere
spring.datasource.username=root
spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# JWT
jwt.secret=Ga/0YweS3dSDxmfFBVKMD+yKltGBDq6uU6eBuqqTE8F/GCcQkaBuZ9WoHAnNw/9NuG+WaZpYDdeqeSvP/6ObsA==
jwt.expiration=86400000